export type WordEntry = {
  hiragana: string;
  patterns: string[];
};

// 形式: [ひらがな, パターン1（ガイド表示）, パターン2, ...]
const WORD_LIST: [string, ...string[]][] = [
  // 自然・天気・季節
  ["そら", "sora"],
  ["くも", "kumo"],
  ["あめ", "ame"],
  ["ゆき", "yuki"],
  ["かぜ", "kaze"],
  ["みず", "mizu"],
  ["うみ", "umi"],
  ["やま", "yama"],
  ["かわ", "kawa"],
  ["もり", "mori"],
  ["いわ", "iwa"],
  ["くさ", "kusa"],
  ["はな", "hana"],
  ["つき", "tuki", "tsuki"],
  ["ほし", "hosi", "hoshi"],
  ["ひる", "hiru"],
  ["よる", "yoru"],
  ["あき", "aki"],
  ["はる", "haru"],
  ["なつ", "natu", "natsu"],
  ["ふゆ", "huyu", "fuyu"],
  ["しも", "simo", "shimo"],
  ["なみ", "nami"],
  ["いけ", "ike"],
  ["つゆ", "tuyu", "tsuyu"],
  ["みね", "mine"],
  ["もや", "moya"],
  ["たに", "tani"],
  ["さと", "sato"],
  ["ぬま", "numa"],
  ["きり", "kiri"],
  ["のき", "noki"],
  ["たけ", "take"],
  ["はた", "hata"],
  // 動物・虫
  ["いぬ", "inu"],
  ["ねこ", "neko"],
  ["とり", "tori"],
  ["むし", "musi", "mushi"],
  ["うし", "usi", "ushi"],
  ["うま", "uma"],
  ["ぶた", "buta"],
  ["やぎ", "yagi"],
  ["かに", "kani"],
  ["たこ", "tako"],
  ["いか", "ika"],
  ["さる", "saru"],
  ["くま", "kuma"],
  ["かめ", "kame"],
  ["へび", "hebi"],
  ["はち", "hati", "hachi"],
  ["あり", "ari"],
  ["きじ", "kiji"],
  ["しか", "sika", "shika"],
  ["すず", "suzu"],
  ["たか", "taka"],
  ["さめ", "same"],
  ["えび", "ebi"],
  ["かも", "kamo"],
  ["はと", "hato"],
  ["こい", "koi"],
  ["ふぐ", "hugu", "fugu"],
  // 食べ物・飲み物
  ["めし", "mesi", "meshi"],
  ["むぎ", "mugi"],
  ["まめ", "mame"],
  ["いも", "imo"],
  ["なし", "nasi", "nashi"],
  ["かき", "kaki"],
  ["もも", "momo"],
  ["うめ", "ume"],
  ["すし", "susi", "sushi"],
  ["にく", "niku"],
  ["たま", "tama"],
  ["みそ", "miso"],
  ["こめ", "kome"],
  ["のり", "nori"],
  ["やき", "yaki"],
  ["こぶ", "kobu"],
  ["たね", "tane"],
  ["きみ", "kimi"],
  ["あわ", "awa"],
  ["ゆず", "yuzu"],
  ["なべ", "nabe"],
  // 体・人
  ["ひと", "hito"],
  ["あし", "asi", "ashi"],
  ["かお", "kao"],
  ["みみ", "mimi"],
  ["くち", "kuti", "kuchi"],
  ["かみ", "kami"],
  ["こし", "kosi", "koshi"],
  ["ゆび", "yubi"],
  ["ひざ", "hiza"],
  ["かた", "kata"],
  ["はだ", "hada"],
  ["むね", "mune"],
  ["なか", "naka"],
  // 場所・建物
  ["てら", "tera"],
  ["まど", "mado"],
  ["えき", "eki"],
  ["みち", "miti", "michi"],
  ["まち", "mati", "machi"],
  ["にわ", "niwa"],
  ["くに", "kuni"],
  ["しろ", "siro", "shiro"],
  ["はし", "hasi", "hashi"],
  ["みせ", "mise"],
  ["やど", "yado"],
  ["いえ", "ie"],
  ["さか", "saka"],
  ["たき", "taki"],
  // 道具・くらし
  ["はこ", "hako"],
  ["かぎ", "kagi"],
  ["たな", "tana"],
  ["かさ", "kasa"],
  ["いす", "isu"],
  ["ふで", "hude", "fude"],
  ["かべ", "kabe"],
  ["ゆか", "yuka"],
  ["やね", "yane"],
  ["あな", "ana"],
  ["つぼ", "tubo", "tsubo"],
  ["かぶ", "kabu"],
  ["かご", "kago"],
  ["ひも", "himo"],
  ["ふた", "huta", "futa"],
  ["たて", "tate"],
  ["いし", "isi", "ishi"],
  ["ふね", "hune", "fune"],
  ["おけ", "oke"],
  ["なわ", "nawa"],
  ["きぬ", "kinu"],
  ["わた", "wata"],
  // 色・方向・ことば
  ["あか", "aka"],
  ["あお", "ao"],
  ["くろ", "kuro"],
  ["ちず", "tizu", "chizu"],
  ["しお", "sio", "shio"],
  ["つち", "tuti", "tsuchi", "tuchi"],
  ["ふじ", "huji", "fuji"],
  ["うえ", "ue"],
  ["した", "sita", "shita"],
  ["まえ", "mae"],
  ["うら", "ura"],
  ["そと", "soto"],
  ["みぎ", "migi"],
  ["きた", "kita"],
  ["みな", "mina"],
  ["にし", "nisi", "nishi"],
  ["そこ", "soko"],
];


export function pickRandom(exclude?: string | Set<string>): WordEntry {
  const pool = exclude
    ? WORD_LIST.filter(w =>
        typeof exclude === "string"
          ? w[0] !== exclude
          : !exclude.has(w[0])
      )
    : WORD_LIST;
  // 全単語使い切ったらリセット（無限ループ防止）
  const source = pool.length > 0 ? pool : WORD_LIST;
  const raw = source[Math.floor(Math.random() * source.length)];
  return { hiragana: raw[0], patterns: raw.slice(1) as string[] };
}
